version: "3"

services:
#  nginx:
#    container_name: nginx
#    image: nginx
#    restart: always
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./configs/conf.d/:/etc/nginx/conf.d/
  mysql:
    image: "mariadb:10.11.2"
    command: [ "--max_connections=1000" ]
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=myroot
      - MYSQL_DATABASE=TTMS
      - MYSQL_USER=TTMS
      - MYSQL_PASSWORD=TTMS
      #- MYSQL_MAX_CONNECTIONS = 300 #暂时不起作用
      - MYSQL_DATABASE=high_frequency
    volumes:
      - ./script/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  Etcd:
    image: "quay.io/coreos/etcd:v3.5.5"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_CTL_API=3
    ports:
      - "2379:2379"
  redis:
    image: "redis:latest"
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "6378:6379"
    volumes:
      - ./script/redis/data:/data
  #启动时有几秒的时间不能工作，吓我一跳，还以为配置哪里错了
  nats1:
    container_name: nats1
    image: nats:latest
    #    entrypoint: /nats-server
    command: --name nats1 --cluster_name JSC --js  --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats2:4245,nats://nats3:4245 -p 4222
    networks:
      - nats
    ports:
      - "4222:4222"
    volumes:
      - ./jetstream-cluster/nats1:/data

  nats2:
    container_name: nats2
    image: nats:latest
    #    entrypoint: /nats-server
    command: --name nats2 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats2:4245,nats://nats3:4245 -p 4222
    networks:
      - nats
    ports:
      - "4223:4222"
    volumes:
      - ./jetstream-cluster/nats2:/data

  nats3:
    container_name: nats3
    image: nats:latest
    #    entrypoint: /nats-server
    command: --name nats3 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats2:4245,nats://nats3:4245 -p 4222
    networks:
      - nats
    ports:
      - "4224:4222"
    volumes:
      - ./jetstream-cluster/nats3:/data

networks:
  nats: { }
