// Code generated by Kitex v0.9.1. DO NOT EDIT.

package orderservice

import (
	order "TTMS/kitex_gen/order"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UpdateOrder(ctx context.Context, Req *order.UpdateOrderRequest, callOptions ...callopt.Option) (r *order.UpdateOrderResponse, err error)
	GetAllOrder(ctx context.Context, Req *order.GetAllOrderRequest, callOptions ...callopt.Option) (r *order.GetAllOrderResponse, err error)
	GetOrderAnalysis(ctx context.Context, Req *order.GetOrderAnalysisRequest, callOptions ...callopt.Option) (r *order.GetOrderAnalysisResponse, err error)
	CommitOrder(ctx context.Context, Req *order.CommitOrderRequest, callOptions ...callopt.Option) (r *order.CommitOrderResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*kClient
}

func (p *kOrderServiceClient) UpdateOrder(ctx context.Context, Req *order.UpdateOrderRequest, callOptions ...callopt.Option) (r *order.UpdateOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOrder(ctx, Req)
}

func (p *kOrderServiceClient) GetAllOrder(ctx context.Context, Req *order.GetAllOrderRequest, callOptions ...callopt.Option) (r *order.GetAllOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAllOrder(ctx, Req)
}

func (p *kOrderServiceClient) GetOrderAnalysis(ctx context.Context, Req *order.GetOrderAnalysisRequest, callOptions ...callopt.Option) (r *order.GetOrderAnalysisResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrderAnalysis(ctx, Req)
}

func (p *kOrderServiceClient) CommitOrder(ctx context.Context, Req *order.CommitOrderRequest, callOptions ...callopt.Option) (r *order.CommitOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommitOrder(ctx, Req)
}
