// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: studio.proto

package studio

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode    int64  `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	StatusMessage string `protobuf:"bytes,2,opt,name=StatusMessage,proto3" json:"StatusMessage,omitempty"`
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BaseResp) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type Studio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	RowsCount  int64  `protobuf:"varint,3,opt,name=RowsCount,proto3" json:"RowsCount,omitempty"`
	ColsCount  int64  `protobuf:"varint,4,opt,name=ColsCount,proto3" json:"ColsCount,omitempty"`
	SeatsCount int64  `protobuf:"varint,5,opt,name=SeatsCount,proto3" json:"SeatsCount,omitempty"`
}

func (x *Studio) Reset() {
	*x = Studio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Studio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Studio) ProtoMessage() {}

func (x *Studio) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Studio.ProtoReflect.Descriptor instead.
func (*Studio) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{1}
}

func (x *Studio) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Studio) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Studio) GetRowsCount() int64 {
	if x != nil {
		return x.RowsCount
	}
	return 0
}

func (x *Studio) GetColsCount() int64 {
	if x != nil {
		return x.ColsCount
	}
	return 0
}

func (x *Studio) GetSeatsCount() int64 {
	if x != nil {
		return x.SeatsCount
	}
	return 0
}

// 添加演出厅
type AddStudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	RowsCount int64  `protobuf:"varint,2,opt,name=RowsCount,proto3" json:"RowsCount,omitempty"`
	ColsCount int64  `protobuf:"varint,3,opt,name=ColsCount,proto3" json:"ColsCount,omitempty"`
}

func (x *AddStudioRequest) Reset() {
	*x = AddStudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStudioRequest) ProtoMessage() {}

func (x *AddStudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStudioRequest.ProtoReflect.Descriptor instead.
func (*AddStudioRequest) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{2}
}

func (x *AddStudioRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddStudioRequest) GetRowsCount() int64 {
	if x != nil {
		return x.RowsCount
	}
	return 0
}

func (x *AddStudioRequest) GetColsCount() int64 {
	if x != nil {
		return x.ColsCount
	}
	return 0
}

type AddStudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *BaseResp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
}

func (x *AddStudioResponse) Reset() {
	*x = AddStudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStudioResponse) ProtoMessage() {}

func (x *AddStudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStudioResponse.ProtoReflect.Descriptor instead.
func (*AddStudioResponse) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{3}
}

func (x *AddStudioResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

// 分页获取演出厅信息
type GetAllStudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current  int32 `protobuf:"varint,1,opt,name=Current,proto3" json:"Current,omitempty"`   //当前页
	PageSize int32 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"` //一页数据条数
}

func (x *GetAllStudioRequest) Reset() {
	*x = GetAllStudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllStudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStudioRequest) ProtoMessage() {}

func (x *GetAllStudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStudioRequest.ProtoReflect.Descriptor instead.
func (*GetAllStudioRequest) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllStudioRequest) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetAllStudioRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllStudioResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64     `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	List  []*Studio `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *GetAllStudioResponseData) Reset() {
	*x = GetAllStudioResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllStudioResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStudioResponseData) ProtoMessage() {}

func (x *GetAllStudioResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStudioResponseData.ProtoReflect.Descriptor instead.
func (*GetAllStudioResponseData) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllStudioResponseData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllStudioResponseData) GetList() []*Studio {
	if x != nil {
		return x.List
	}
	return nil
}

type GetAllStudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *BaseResp                 `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	Data     *GetAllStudioResponseData `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetAllStudioResponse) Reset() {
	*x = GetAllStudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllStudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStudioResponse) ProtoMessage() {}

func (x *GetAllStudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStudioResponse.ProtoReflect.Descriptor instead.
func (*GetAllStudioResponse) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllStudioResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *GetAllStudioResponse) GetData() *GetAllStudioResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取z指定演出厅信息
type GetStudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetStudioRequest) Reset() {
	*x = GetStudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudioRequest) ProtoMessage() {}

func (x *GetStudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudioRequest.ProtoReflect.Descriptor instead.
func (*GetStudioRequest) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{7}
}

func (x *GetStudioRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *BaseResp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	Result   *Studio   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetStudioResponse) Reset() {
	*x = GetStudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudioResponse) ProtoMessage() {}

func (x *GetStudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudioResponse.ProtoReflect.Descriptor instead.
func (*GetStudioResponse) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{8}
}

func (x *GetStudioResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *GetStudioResponse) GetResult() *Studio {
	if x != nil {
		return x.Result
	}
	return nil
}

// 修改指定演出厅
type UpdateStudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	RowsCount int64  `protobuf:"varint,2,opt,name=RowsCount,proto3" json:"RowsCount,omitempty"`
	ColsCount int64  `protobuf:"varint,3,opt,name=ColsCount,proto3" json:"ColsCount,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *UpdateStudioRequest) Reset() {
	*x = UpdateStudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudioRequest) ProtoMessage() {}

func (x *UpdateStudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudioRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudioRequest) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStudioRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStudioRequest) GetRowsCount() int64 {
	if x != nil {
		return x.RowsCount
	}
	return 0
}

func (x *UpdateStudioRequest) GetColsCount() int64 {
	if x != nil {
		return x.ColsCount
	}
	return 0
}

func (x *UpdateStudioRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateStudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *BaseResp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
}

func (x *UpdateStudioResponse) Reset() {
	*x = UpdateStudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudioResponse) ProtoMessage() {}

func (x *UpdateStudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudioResponse.ProtoReflect.Descriptor instead.
func (*UpdateStudioResponse) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStudioResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

// 删除指定演出厅
type DeleteStudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *DeleteStudioRequest) Reset() {
	*x = DeleteStudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudioRequest) ProtoMessage() {}

func (x *DeleteStudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudioRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudioRequest) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteStudioRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteStudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *BaseResp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
}

func (x *DeleteStudioResponse) Reset() {
	*x = DeleteStudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudioResponse) ProtoMessage() {}

func (x *DeleteStudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudioResponse.ProtoReflect.Descriptor instead.
func (*DeleteStudioResponse) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteStudioResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type Seat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	StudioId int64 `protobuf:"varint,2,opt,name=StudioId,proto3" json:"StudioId,omitempty"` //座位所在的演出厅ID
	Row      int64 `protobuf:"varint,3,opt,name=Row,proto3" json:"Row,omitempty"`
	Col      int64 `protobuf:"varint,4,opt,name=Col,proto3" json:"Col,omitempty"`
	Status   int64 `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"` //0-不是座位，1-有座位，9-损坏的座位
}

func (x *Seat) Reset() {
	*x = Seat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{13}
}

func (x *Seat) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Seat) GetStudioId() int64 {
	if x != nil {
		return x.StudioId
	}
	return 0
}

func (x *Seat) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Seat) GetCol() int64 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *Seat) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 添加指定座位
type AddSeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudioId int64 `protobuf:"varint,1,opt,name=StudioId,proto3" json:"StudioId,omitempty"`
	Row      int64 `protobuf:"varint,2,opt,name=Row,proto3" json:"Row,omitempty"`
	Col      int64 `protobuf:"varint,3,opt,name=Col,proto3" json:"Col,omitempty"`
	Status   int64 `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"` //0-不是座位，1-有座位，9-损坏的座位
}

func (x *AddSeatRequest) Reset() {
	*x = AddSeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSeatRequest) ProtoMessage() {}

func (x *AddSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSeatRequest.ProtoReflect.Descriptor instead.
func (*AddSeatRequest) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{14}
}

func (x *AddSeatRequest) GetStudioId() int64 {
	if x != nil {
		return x.StudioId
	}
	return 0
}

func (x *AddSeatRequest) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *AddSeatRequest) GetCol() int64 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *AddSeatRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddSeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *BaseResp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
}

func (x *AddSeatResponse) Reset() {
	*x = AddSeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSeatResponse) ProtoMessage() {}

func (x *AddSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSeatResponse.ProtoReflect.Descriptor instead.
func (*AddSeatResponse) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{15}
}

func (x *AddSeatResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

// 分页获取座位信息
type GetAllSeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudioId int64 `protobuf:"varint,1,opt,name=StudioId,proto3" json:"StudioId,omitempty"`
	Current  int32 `protobuf:"varint,2,opt,name=Current,proto3" json:"Current,omitempty"`   //当前页
	PageSize int32 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"` //一页数据条数
}

func (x *GetAllSeatRequest) Reset() {
	*x = GetAllSeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSeatRequest) ProtoMessage() {}

func (x *GetAllSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSeatRequest.ProtoReflect.Descriptor instead.
func (*GetAllSeatRequest) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{16}
}

func (x *GetAllSeatRequest) GetStudioId() int64 {
	if x != nil {
		return x.StudioId
	}
	return 0
}

func (x *GetAllSeatRequest) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetAllSeatRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllSeatResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64   `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	List  []*Seat `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *GetAllSeatResponseData) Reset() {
	*x = GetAllSeatResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSeatResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSeatResponseData) ProtoMessage() {}

func (x *GetAllSeatResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSeatResponseData.ProtoReflect.Descriptor instead.
func (*GetAllSeatResponseData) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllSeatResponseData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllSeatResponseData) GetList() []*Seat {
	if x != nil {
		return x.List
	}
	return nil
}

type GetAllSeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *BaseResp               `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	Data     *GetAllSeatResponseData `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetAllSeatResponse) Reset() {
	*x = GetAllSeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSeatResponse) ProtoMessage() {}

func (x *GetAllSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSeatResponse.ProtoReflect.Descriptor instead.
func (*GetAllSeatResponse) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{18}
}

func (x *GetAllSeatResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *GetAllSeatResponse) GetData() *GetAllSeatResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 修改指定座位
type UpdateSeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudioId int64 `protobuf:"varint,1,opt,name=StudioId,proto3" json:"StudioId,omitempty"`
	Row      int64 `protobuf:"varint,2,opt,name=Row,proto3" json:"Row,omitempty"`
	Col      int64 `protobuf:"varint,3,opt,name=Col,proto3" json:"Col,omitempty"`
	Status   int64 `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"` //修改后座位的新状态
}

func (x *UpdateSeatRequest) Reset() {
	*x = UpdateSeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatRequest) ProtoMessage() {}

func (x *UpdateSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatRequest.ProtoReflect.Descriptor instead.
func (*UpdateSeatRequest) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateSeatRequest) GetStudioId() int64 {
	if x != nil {
		return x.StudioId
	}
	return 0
}

func (x *UpdateSeatRequest) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *UpdateSeatRequest) GetCol() int64 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *UpdateSeatRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateSeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *BaseResp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
}

func (x *UpdateSeatResponse) Reset() {
	*x = UpdateSeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatResponse) ProtoMessage() {}

func (x *UpdateSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatResponse.ProtoReflect.Descriptor instead.
func (*UpdateSeatResponse) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateSeatResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

// 删除指定座位
type DeleteSeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudioId int64 `protobuf:"varint,1,opt,name=StudioId,proto3" json:"StudioId,omitempty"`
	Row      int64 `protobuf:"varint,2,opt,name=Row,proto3" json:"Row,omitempty"`
	Col      int64 `protobuf:"varint,3,opt,name=Col,proto3" json:"Col,omitempty"`
}

func (x *DeleteSeatRequest) Reset() {
	*x = DeleteSeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSeatRequest) ProtoMessage() {}

func (x *DeleteSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSeatRequest.ProtoReflect.Descriptor instead.
func (*DeleteSeatRequest) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteSeatRequest) GetStudioId() int64 {
	if x != nil {
		return x.StudioId
	}
	return 0
}

func (x *DeleteSeatRequest) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *DeleteSeatRequest) GetCol() int64 {
	if x != nil {
		return x.Col
	}
	return 0
}

type DeleteSeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *BaseResp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
}

func (x *DeleteSeatResponse) Reset() {
	*x = DeleteSeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studio_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSeatResponse) ProtoMessage() {}

func (x *DeleteSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studio_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSeatResponse.ProtoReflect.Descriptor instead.
func (*DeleteSeatResponse) Descriptor() ([]byte, []int) {
	return file_studio_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteSeatResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

var File_studio_proto protoreflect.FileDescriptor

var file_studio_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x22, 0x50, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x75,
	0x64, 0x69, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x6f, 0x77, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x52, 0x6f, 0x77, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x73, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x6f, 0x6c, 0x73, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x53, 0x65, 0x61, 0x74, 0x73, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x62, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52,
	0x6f, 0x77, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x52, 0x6f, 0x77, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6c,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x6f,
	0x6c, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x41, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x52, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4b, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x54, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x22, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f,
	0x2e, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x7a, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x69, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x26, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x75, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x52, 0x6f, 0x77, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x52, 0x6f, 0x77, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x43, 0x6f, 0x6c, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x43, 0x6f, 0x6c, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x44, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x75, 0x64,
	0x69, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x6e, 0x0a, 0x04, 0x53, 0x65, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x6f, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x43, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x68, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x52,
	0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x43, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3f, 0x0a, 0x0f,
	0x41, 0x64, 0x64, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2c, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x52, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x65, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x50, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65,
	0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x74,
	0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x76, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x52, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6b,
	0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x52, 0x6f,
	0x77, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x43, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x42, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x53, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x52,
	0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x43, 0x6f, 0x6c, 0x22, 0x42, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65,
	0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32, 0x91, 0x05, 0x0a, 0x0d, 0x53, 0x74, 0x75,
	0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x41, 0x64,
	0x64, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x18, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f,
	0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x1b,
	0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x75, 0x64, 0x69,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x1b, 0x2e, 0x73, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69,
	0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x1b, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69,
	0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x53, 0x65, 0x61, 0x74,
	0x12, 0x16, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69,
	0x6f, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x61,
	0x74, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69,
	0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x45, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x12,
	0x19, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x75,
	0x64, 0x69, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x18, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64,
	0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15,
	0x54, 0x54, 0x4d, 0x53, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x73,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_studio_proto_rawDescOnce sync.Once
	file_studio_proto_rawDescData = file_studio_proto_rawDesc
)

func file_studio_proto_rawDescGZIP() []byte {
	file_studio_proto_rawDescOnce.Do(func() {
		file_studio_proto_rawDescData = protoimpl.X.CompressGZIP(file_studio_proto_rawDescData)
	})
	return file_studio_proto_rawDescData
}

var file_studio_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_studio_proto_goTypes = []interface{}{
	(*BaseResp)(nil),                 // 0: studio.BaseResp
	(*Studio)(nil),                   // 1: studio.Studio
	(*AddStudioRequest)(nil),         // 2: studio.AddStudioRequest
	(*AddStudioResponse)(nil),        // 3: studio.AddStudioResponse
	(*GetAllStudioRequest)(nil),      // 4: studio.GetAllStudioRequest
	(*GetAllStudioResponseData)(nil), // 5: studio.GetAllStudioResponseData
	(*GetAllStudioResponse)(nil),     // 6: studio.GetAllStudioResponse
	(*GetStudioRequest)(nil),         // 7: studio.GetStudioRequest
	(*GetStudioResponse)(nil),        // 8: studio.GetStudioResponse
	(*UpdateStudioRequest)(nil),      // 9: studio.UpdateStudioRequest
	(*UpdateStudioResponse)(nil),     // 10: studio.UpdateStudioResponse
	(*DeleteStudioRequest)(nil),      // 11: studio.DeleteStudioRequest
	(*DeleteStudioResponse)(nil),     // 12: studio.DeleteStudioResponse
	(*Seat)(nil),                     // 13: studio.Seat
	(*AddSeatRequest)(nil),           // 14: studio.AddSeatRequest
	(*AddSeatResponse)(nil),          // 15: studio.AddSeatResponse
	(*GetAllSeatRequest)(nil),        // 16: studio.GetAllSeatRequest
	(*GetAllSeatResponseData)(nil),   // 17: studio.GetAllSeatResponseData
	(*GetAllSeatResponse)(nil),       // 18: studio.GetAllSeatResponse
	(*UpdateSeatRequest)(nil),        // 19: studio.UpdateSeatRequest
	(*UpdateSeatResponse)(nil),       // 20: studio.UpdateSeatResponse
	(*DeleteSeatRequest)(nil),        // 21: studio.DeleteSeatRequest
	(*DeleteSeatResponse)(nil),       // 22: studio.DeleteSeatResponse
}
var file_studio_proto_depIdxs = []int32{
	0,  // 0: studio.AddStudioResponse.BaseResp:type_name -> studio.BaseResp
	1,  // 1: studio.GetAllStudioResponseData.List:type_name -> studio.Studio
	0,  // 2: studio.GetAllStudioResponse.BaseResp:type_name -> studio.BaseResp
	5,  // 3: studio.GetAllStudioResponse.Data:type_name -> studio.GetAllStudioResponseData
	0,  // 4: studio.GetStudioResponse.BaseResp:type_name -> studio.BaseResp
	1,  // 5: studio.GetStudioResponse.result:type_name -> studio.Studio
	0,  // 6: studio.UpdateStudioResponse.BaseResp:type_name -> studio.BaseResp
	0,  // 7: studio.DeleteStudioResponse.BaseResp:type_name -> studio.BaseResp
	0,  // 8: studio.AddSeatResponse.BaseResp:type_name -> studio.BaseResp
	13, // 9: studio.GetAllSeatResponseData.List:type_name -> studio.Seat
	0,  // 10: studio.GetAllSeatResponse.BaseResp:type_name -> studio.BaseResp
	17, // 11: studio.GetAllSeatResponse.Data:type_name -> studio.GetAllSeatResponseData
	0,  // 12: studio.UpdateSeatResponse.BaseResp:type_name -> studio.BaseResp
	0,  // 13: studio.DeleteSeatResponse.BaseResp:type_name -> studio.BaseResp
	2,  // 14: studio.StudioService.AddStudio:input_type -> studio.AddStudioRequest
	4,  // 15: studio.StudioService.GetAllStudio:input_type -> studio.GetAllStudioRequest
	9,  // 16: studio.StudioService.UpdateStudio:input_type -> studio.UpdateStudioRequest
	11, // 17: studio.StudioService.DeleteStudio:input_type -> studio.DeleteStudioRequest
	14, // 18: studio.StudioService.AddSeat:input_type -> studio.AddSeatRequest
	16, // 19: studio.StudioService.GetAllSeat:input_type -> studio.GetAllSeatRequest
	19, // 20: studio.StudioService.UpdateSeat:input_type -> studio.UpdateSeatRequest
	21, // 21: studio.StudioService.DeleteSeat:input_type -> studio.DeleteSeatRequest
	7,  // 22: studio.StudioService.GetStudio:input_type -> studio.GetStudioRequest
	3,  // 23: studio.StudioService.AddStudio:output_type -> studio.AddStudioResponse
	6,  // 24: studio.StudioService.GetAllStudio:output_type -> studio.GetAllStudioResponse
	10, // 25: studio.StudioService.UpdateStudio:output_type -> studio.UpdateStudioResponse
	12, // 26: studio.StudioService.DeleteStudio:output_type -> studio.DeleteStudioResponse
	15, // 27: studio.StudioService.AddSeat:output_type -> studio.AddSeatResponse
	18, // 28: studio.StudioService.GetAllSeat:output_type -> studio.GetAllSeatResponse
	20, // 29: studio.StudioService.UpdateSeat:output_type -> studio.UpdateSeatResponse
	22, // 30: studio.StudioService.DeleteSeat:output_type -> studio.DeleteSeatResponse
	8,  // 31: studio.StudioService.GetStudio:output_type -> studio.GetStudioResponse
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_studio_proto_init() }
func file_studio_proto_init() {
	if File_studio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_studio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Studio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllStudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllStudioResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllStudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllSeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllSeatResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllSeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studio_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_studio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_studio_proto_goTypes,
		DependencyIndexes: file_studio_proto_depIdxs,
		MessageInfos:      file_studio_proto_msgTypes,
	}.Build()
	File_studio_proto = out.File
	file_studio_proto_rawDesc = nil
	file_studio_proto_goTypes = nil
	file_studio_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.9.1. DO NOT EDIT.

type StudioService interface {
	AddStudio(ctx context.Context, req *AddStudioRequest) (res *AddStudioResponse, err error)
	GetAllStudio(ctx context.Context, req *GetAllStudioRequest) (res *GetAllStudioResponse, err error)
	UpdateStudio(ctx context.Context, req *UpdateStudioRequest) (res *UpdateStudioResponse, err error)
	DeleteStudio(ctx context.Context, req *DeleteStudioRequest) (res *DeleteStudioResponse, err error)
	AddSeat(ctx context.Context, req *AddSeatRequest) (res *AddSeatResponse, err error)
	GetAllSeat(ctx context.Context, req *GetAllSeatRequest) (res *GetAllSeatResponse, err error)
	UpdateSeat(ctx context.Context, req *UpdateSeatRequest) (res *UpdateSeatResponse, err error)
	DeleteSeat(ctx context.Context, req *DeleteSeatRequest) (res *DeleteSeatResponse, err error)
	GetStudio(ctx context.Context, req *GetStudioRequest) (res *GetStudioResponse, err error)
}
